name: Java CI with Maven and JavaFX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the repository
    - uses: actions/checkout@v4
    
    # Step 2: Set up JDK 11 (since your pom.xml specifies Java 11)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    # Step 3: Build the project with Maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    
    # Optional Step: Upload the dependency graph to GitHub for better Dependabot alerts
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
